---
abstract: 'Simple Perl data structure browser Padre'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Locale::Msgfmt: 0.14
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-DataWalker
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Padre: 0.47
  Wx::Perl::DataWalker: 0.02
  YAML::XS: 0
  perl: 5.8.0
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-DataWalker/
version: 0.02
